apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-join
  name: bluejay-join
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-join
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30601
  selector:
    app: bluejay-join
