---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-collector-events
  name: bluejay-collector-events
  namespace: governify-bluejay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-collector-events
  template:
    metadata:
      labels:
        app: bluejay-collector-events
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: REDIS_HOSTNAME
              value: "bluejay-redis-ec"
            - name: KEY_SCOPE_MANAGER
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_SCOPE_MANAGER
            - name: KEY_GITHUB
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_GITHUB
            - name: KEY_PIVOTAL
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_PIVOTAL
            - name: KEY_TRAVIS_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_TRAVIS_PUBLIC
            - name: KEY_TRAVIS_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_TRAVIS_PRIVATE
            - name: KEY_HEROKU
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_HEROKU
            - name: KEY_CODECLIMATE
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: KEY_CODECLIMATE
            - name: NEW_RELIC_APP_NAME
              value: Bluejay-Collector-Events
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: NEW_RELIC_LICENSE_KEY
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: GOV_INFRASTRUCTURE

          image: governify/collector-events:v1.22.3
          imagePullPolicy: Always
          name: bluejay-collector-events
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 900Mi
