apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-collector-events
  name: bluejay-collector-events
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-collector-events
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30500
  selector:
    app: bluejay-collector-events
