apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-director
  name: bluejay-director
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-director
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30800
  selector:
    app: bluejay-director
