kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bluejay-tpa-manager
  namespace: governify-bluejay
  labels:
    app: bluejay-tpa-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
