---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bluejay-redis-ec
  namespace: governify-bluejay
  labels:
    app: bluejay-redis-ec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---

