apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-redis-ec
  name: bluejay-redis-ec
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-redis-ec
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 30003

  selector:
    app: bluejay-redis-ec
