apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-reporter
  name: bluejay-reporter
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-reporter
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30300
  selector:
    app: bluejay-reporter
