apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-scope-manager
  name: bluejay-scope-manager
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-scope-manager
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30700
  selector:
    app: bluejay-scope-manager
