---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-render
  name: bluejay-render
  namespace: governify-bluejay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-render
  template:
    metadata:
      labels:
        app: bluejay-render
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: LOGIN_USER
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: USER_RENDER
            - name: LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bluejay-secrets
                  key: PASS_RENDER
            - name: DEFAULT_VIEW
              value: "http://bluejay-assets-manager/api/v1/public/renders/index/view.html"
            - name: DEFAULT_CONTROLLER
              value: "http://bluejay-assets-manager/api/v1/public/renders/index/controller.js"
            - name: DEFAULT_MODEL
              value: "http://bluejay-assets-manager/api/v1/public/renders/index/model.json"
            - name: LAYOUT
              value: bootstrap5.html
            - name: GOV_INFRASTRUCTURE
              valueFrom:
                secretKeyRef:
                  key: GOV_INFRASTRUCTURE
                  name: bluejay-secrets
          image: governify/render:v2.3.0
          imagePullPolicy: Always
          name: bluejay-render
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - mountPath: /opt/app/logs
              name: bluejay-render-logs
      volumes:
        - name: bluejay-render-logs
          persistentVolumeClaim:
            claimName: bluejay-render
