apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-render
  name: bluejay-render
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-render
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30100
  selector:
    app: bluejay-render
