apiVersion: v1
kind: Service
metadata:
  labels:
    app: bluejay-registry
    idle: "true"
  name: bluejay-registry
  namespace: governify-bluejay
spec:
  type: NodePort
  ports:
    - name: bluejay-registry
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30400
  selector:
    app: bluejay-registry
