apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluejay-mongo-registry
  name: bluejay-mongo-registry
  namespace: governify-bluejay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluejay-mongo-registry
  template:
    metadata:
      labels:
        app: bluejay-mongo-registry
    spec:
      containers:
        - image: mongo:6.0
          imagePullPolicy: Always
          name: bluejay-mongo-registry
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: bluejay-mongo-registry-db-volume
      volumes:
        - name: bluejay-mongo-registry-db-volume
          persistentVolumeClaim:
            claimName: bluejay-mongo-registry
